version: '3.9'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    depends_on:
      - pgsql
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
      - SESSION_EXPIRY_SECONDS=2592000
    env_file:
      - ./.env
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/rails server -p 3000 -b 0.0.0.0"

  pgsql:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

volumes:
  postgres:
  node_modules:
  packs:
  cache:
  bundle:
