json.id assigned_curriculum.id
json.name assigned_curriculum.curriculum.name
json.description assigned_curriculum.curriculum.description
json.start_datetime assigned_curriculum.start_datetime
json.end_datetime assigned_curriculum.end_datetime
json.completed assigned_curriculum.completed
